### PR TITLE
LPS-184353 Paginate properly Placed Orders on Customer Dashboard

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-184353

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
This PR depends on: https://github.com/danvb112/liferay-portal/pull/69

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Hey @danvb112, I wasn't able to test your PR. This is rebased on some old commits, I tried applying only the last commit on top of what we have on BChan's master, but it's crashing the Customer Dashboard and I couldn't fix it quickly. Since we aligned with Matt to work on those tasks until today, I'm going to return that task to open and we can leave it for the Solutions team to work on, ok? Thanks :)

**Pull request closed without merging**
