### PR TITLE
LPS-183117 Filter only Cloud and DXP orders in the Customer Dashboard and create Solutions section

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-183117

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
@danvb112 I think you missed the part of creating the Marketplace Product Type when creating a new app.

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/134495

**Pull request closed without merging**
