### PR TITLE
LPS-183886 Refactor ReviewAndSubmitAppPage component to get new values

### PR DESCRIPTION
**Pull request by danvb112**
Related Issues: 

https://issues.liferay.com/browse/LPS-183886
https://issues.liferay.com/browse/LPS-184607
https://issues.liferay.com/browse/LPS-183888
https://issues.liferay.com/browse/LPS-183887

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/135027

**Pull request closed without merging**
