### PR TITLE
LPS-181743 Make NextStepsPage generic to reuse code

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue:
https://issues.liferay.com/browse/LPS-181740
https://issues.liferay.com/browse/LPS-181741
https://issues.liferay.com/browse/LPS-181921
https://issues.liferay.com/browse/LPS-181743

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Review by alinedoleron — CHANGES_REQUESTED** [review]

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/133984

**Pull request closed without merging**
